### ISSUE TITLE
Documentation for Fixtures

### ISSUE THREAD

**Issue by Bendihossan** [zand3rs/sails-test-helper#3]
I can't find any documentation on what uses the `fixtures/` directory that `sails-test-helper init` generates.

Some things I'd expect would be:
- what format do the files need to be written in?
- how are they used?
- some examples

**Comment by zand3rs** [comment]
It's just part of the directory structure that you can use for your test requirements. You can put anything in there usually assets such as images, static data, etc that you use in your test cases. There's no strict guidelines on how to use it. It's just there for convenience :)

**Comment by Bendihossan** [comment]
So say I put static data in there, how does that integrate with Sails? Or is it literally just a folder?

**Comment by zand3rs** [comment]
No direct relation to Sails. It's basically for your tests use.

**Comment by zand3rs** [comment]
Say you have a controller that accepts a file or image to be uploaded, you can put a sample image in the fixture directory so you can use in your upload tests.

**Comment by Bendihossan** [comment]
Righto, thank you!
